[package]
name = "rust-example"
version = "0.1.0"
[dependencies.sdl2]
version = "0.32.2"
default-features = false
features = ["ttf"]
[dependencies]
rand = "0.7.0"

[[bin]]
name = "server"
path = "src/server/server.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"